updated latest wdls
Intel-HLS/BIGstack pull request #25
Opened 2024-03-22 04:35 UTC by priyankasebastian

2024-03-27 14:58 UTC, mateuszsnowak requested changes

2024-03-27 14:58 UTC, mateuszsnowak commented on 20k_Throughput-run/WDL/Utilities.wdl
> +}
Missing newline at end of file

2024-03-27 14:58 UTC, mateuszsnowak commented on 20k_Throughput-run/WDL/BamProcessing.wdl.bk
> +version 1.0
Please remove this file

2024-04-08 20:36 UTC, priyankasebastian commented
@mateuszsnowak made the changes suggested. Should be good to merge.

2024-04-09 15:40 UTC, mateuszsnowak approved these changes

2024-04-09 15:41 UTC, merged